# Generated by Django 5.0.4 on 2024-04-26 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitem',
            old_name='invoice',
            new_name='inv',
        ),
    ]
