# Generated by Django 5.0.4 on 2024-04-29 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_invoice_invitem_inv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitem',
            name='inv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.invoice'),
        ),
    ]
