# Generated by Django 5.0.4 on 2024-05-01 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_invitem_inv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitem',
            name='inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.invoice'),
        ),
    ]
